### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by filipemeneses** [yovanoc/cookiejs#1]
Some instructions are useful, installation, how it works, usage

**Comment by yovanoc** [comment]
This project is not functional. I just start to develop it.  It will soon be something like this: https://github.com/yovanoc/cookietouch for the UI. But not for DofusTouch, for Dofus PC instead

**Comment by filipemeneses** [comment]
Wooa, very elaborated stuff. I'm looking for it, to some stage where I can contribute.

**Comment by yovanoc** [comment]
Feel free to join the Cookie Project discord https://discord.gg/swU74Fm
A lot of French people but we can speak English :) soon I will open a website and forum for the DofusTouch and this future DofusPC Bot :)

**Comment by filipemeneses** [comment]
Oh, thanks! I'll join in.
